### ISSUE TITLE
loading caps on the crystal

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#58]
@mck1117 says "loading caps on the crystal should be 8pF instead of 20pF"

**Comment by mck1117** [comment]
confirmed - 8pf caps function properly

**Comment by jharvey** [comment]
mck1117, have you seen the note on page 5 of Frankenso? I have some notes and a reference note when we were trying to figure out this intermittent clock issue. See below snippet which is on the Frankenso schematic. 
<code>
http://www.crystek.com/documents/appnotes/Pierce-GateIntroduction.pdf
PCB per predictions with SaturnPCB has less then 3.5pF traces, 
TPIC pins assumed 5pF
ESR = 80ohms max
Rf = 2meg could be between 1meg and 10meg.
Cload should be 18pF per XTAL datasheet
Cload = ([Cin+C1][C2+Cout])/(Cin+C1+C2_Cout)+PCBstray
Cload = ([5+24][24+5])/(5+24+24+5)+3.5= 18.0pF
C1=C2=C166=C167 = 24pF
Rs = 1/(2piFC2) = 1/(2*pi*8MHz*24pF) = 829ohms, 820ohms is close enough = R177
</code>

I think we technically for this one, we want 4pF not 8pF. See my calcs from here
https://docs.google.com/spreadsheets/d/1O6-u6T_O083pT9SEm70DGKKy6YZJ89tGeXWsZTZnmM4/edit?usp=sharing

**Comment by mck1117** [comment]
I hadn’t seen that yet, no. The boards I’ve assembled so far have 8pF caps, and seem to work fine, fwiw. Is there a way to empirically measure whether the crystal is over or under loaded? I have a 200mhz scope at my disposal, and a 4ch/2ghz one at work if I need it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jharvey** [comment]
I don't know a way to measure if the loading is proper. I understand the problem is mostly a failure to start issue. If you change your pF's you can wander the 8MHz slightly, but I don't think we care about the slight warping. I guess we could measure it bey building 1k boards and see if they all start at the min and max temperatures. If yours is starting, with 8pF then it's probably fine. I see 4.7pF is available, so I updated the BOM and schematic to call for that.
